PRODUCT_COPY_FILES += \
	packages/apps/trigtop/google/etc/preferred-apps/google.xml:system/etc/preferred-apps/google.xml \
	packages/apps/trigtop/google/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
	packages/apps/trigtop/google/etc/permissions/tablet_core_hardware.xml:system/etc/permissions/tablet_core_hardware.xml \
	packages/apps/trigtop/google/etc/permissions/com.google.android.dialer.support.xml:system/etc/permissions/com.google.android.dialer.support.xml \
	packages/apps/trigtop/google/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml \
	packages/apps/trigtop/google/etc/sysconfig/google.xml:system/etc/sysconfig/google.xml \
	packages/apps/trigtop/google/priv-app/ConfigUpdater/ConfigUpdater.apk:system/priv-app/ConfigUpdater/ConfigUpdater.apk \
	packages/apps/trigtop/google/priv-app/GoogleServicesFramework/GoogleServicesFramework.apk:system/priv-app/GoogleServicesFramework/GoogleServicesFramework.apk \
	packages/apps/trigtop/google/priv-app/GoogleLoginService/GoogleLoginService.apk:system/priv-app/GoogleLoginService/GoogleLoginService.apk \
	packages/apps/trigtop/google/priv-app/Phonesky/Phonesky.apk:system/priv-app/Phonesky/Phonesky.apk \
	packages/apps/trigtop/google/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk:system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk \
	packages/apps/trigtop/google/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libsslwrapper_jni.so:system/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libsslwrapper_jni.so \
	packages/apps/trigtop/google/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libwearable-selector.so:system/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libwearable-selector.so \
	packages/apps/trigtop/google/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libAppDataSearch.so:system/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libAppDataSearch.so \
	packages/apps/trigtop/google/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libjgcastservice.so:system/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libjgcastservice.so \
	packages/apps/trigtop/google/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libleveldbjni.so:system/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libleveldbjni.so \
	packages/apps/trigtop/google/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libNearbyApp.so:system/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libNearbyApp.so \
	packages/apps/trigtop/google/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libgcastv2_support.so:system/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libgcastv2_support.so \
	packages/apps/trigtop/google/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libgoogle-ocrclient-v3.so:system/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libgoogle-ocrclient-v3.so \
	packages/apps/trigtop/google/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libgcastv2_base.so:system/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libgcastv2_base.so \
	packages/apps/trigtop/google/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libWhisper.so:system/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libWhisper.so \
	packages/apps/trigtop/google/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libconscrypt_gmscore_jni.so:system/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libconscrypt_gmscore_jni.so \
	packages/apps/trigtop/google/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libgmscore.so:system/priv-app/PrebuiltGmsCore/lib/armeabi-v7a/libgmscore.so \
	packages/apps/trigtop/google/priv-app/GoogleBackupTransport/GoogleBackupTransport.apk:system/priv-app/GoogleBackupTransport/GoogleBackupTransport.apk \
	packages/apps/trigtop/google/priv-app/GooglePartnerSetup/GooglePartnerSetup.apk:system/priv-app/GooglePartnerSetup/GooglePartnerSetup.apk \
	packages/apps/trigtop/google/priv-app/GoogleOneTimeInitializer/GoogleOneTimeInitializer.apk:system/priv-app/GoogleOneTimeInitializer/GoogleOneTimeInitializer.apk \
	packages/apps/trigtop/google/priv-app/GoogleFeedback/GoogleFeedback.apk:system/priv-app/GoogleFeedback/GoogleFeedback.apk \
	packages/apps/trigtop/google/lib/libjni_keyboarddecoder.so:system/lib/libjni_keyboarddecoder.so \
	packages/apps/trigtop/google/lib/libjni_latinimegoogle.so:system/lib/libjni_latinimegoogle.so \
	packages/apps/trigtop/google/framework/com.google.android.maps.jar:system/framework/com.google.android.maps.jar \
	packages/apps/trigtop/google/framework/com.google.android.dialer.support.jar:system/framework/com.google.android.dialer.support.jar \
	packages/apps/trigtop/google/framework/com.google.android.media.effects.jar:system/framework/com.google.android.media.effects.jar \
	packages/apps/trigtop/google/app/GoogleTTS/GoogleTTS.apk:system/app/GoogleTTS/GoogleTTS.apk \
	packages/apps/trigtop/google/app/GoogleTTS/lib/armeabi-v7a/libtts_android.so:system/app/GoogleTTS/lib/armeabi-v7a/libtts_android.so \
	packages/apps/trigtop/google/app/GoogleTTS/lib/armeabi-v7a/libtts_android_neon.so:system/app/GoogleTTS/lib/armeabi-v7a/libtts_android_neon.so \
	packages/apps/trigtop/google/app/GoogleCalendarSyncAdapter/GoogleCalendarSyncAdapter.apk:system/app/GoogleCalendarSyncAdapter/GoogleCalendarSyncAdapter.apk \
	packages/apps/trigtop/google/app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk:system/app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk
